const DISCOVER_WEBVIEW_VECTOR_STYLE = Object.freeze({
  version: 8,
  glyphs: "https://tiles.basemaps.cartocdn.com/fonts/{fontstack}/{range}.pbf",
  sources: {
    carto: {
      type: "vector",
      url: "https://tiles.basemaps.cartocdn.com/vector/carto.streets/v1/tiles.json",
    },
  },
  layers: [
    {
      id: "background",
      type: "background",
      paint: {
        "background-color": "#f7f5f0",
      },
    },
    {
      id: "landcover",
      type: "fill",
      source: "carto",
      "source-layer": "landcover",
      filter: [
        "any",
        ["==", "class", "wood"],
        ["==", "class", "grass"],
        ["==", "subclass", "recreation_ground"],
      ],
      paint: {
        "fill-color": "rgba(229, 236, 226, 0.72)",
      },
    },
    {
      id: "park",
      type: "fill",
      source: "carto",
      "source-layer": "park",
      minzoom: 7,
      paint: {
        "fill-color": "rgba(227, 236, 223, 0.84)",
        "fill-antialias": true,
      },
    },
    {
      id: "landuse-residential",
      type: "fill",
      source: "carto",
      "source-layer": "landuse",
      minzoom: 6,
      filter: ["==", "class", "residential"],
      paint: {
        "fill-color": "rgba(241, 239, 234, 0.78)",
      },
    },
    {
      id: "water",
      type: "fill",
      source: "carto",
      "source-layer": "water",
      filter: ["==", "$type", "Polygon"],
      paint: {
        "fill-color": "#d8e3e7",
        "fill-antialias": true,
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "carto",
      "source-layer": "waterway",
      paint: {
        "line-color": "#c6d4da",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          0.5,
          12,
          1.25,
          15,
          2.5,
          17,
          4,
        ],
      },
    },
    {
      id: "building",
      type: "fill",
      source: "carto",
      "source-layer": "building",
      minzoom: 15,
      paint: {
        "fill-color": "#e4ded6",
        "fill-antialias": true,
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          15,
          0.45,
          16,
          0.9,
        ],
      },
    },
    {
      id: "road-major-case",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      filter: ["in", "class", "motorway", "trunk", "primary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#ddd5cb",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          0.8,
          10,
          1.6,
          12,
          3.4,
          14,
          5.8,
          16,
          10,
          18,
          17,
        ],
      },
    },
    {
      id: "road-major-fill",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      filter: ["in", "class", "motorway", "trunk", "primary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#fffdf9",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          7,
          0.3,
          10,
          1,
          12,
          2.3,
          14,
          4.3,
          16,
          8.1,
          18,
          13.6,
        ],
      },
    },
    {
      id: "road-secondary-case",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      filter: ["in", "class", "secondary", "tertiary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#e4ddd4",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          0.8,
          12,
          1.6,
          13,
          2.8,
          14,
          4.8,
          16,
          8,
          18,
          14,
        ],
      },
    },
    {
      id: "road-secondary-fill",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      filter: ["in", "class", "secondary", "tertiary"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#fcfbf8",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          11,
          0.2,
          12,
          0.9,
          13,
          1.8,
          14,
          3.2,
          16,
          6.2,
          18,
          11.5,
        ],
      },
    },
    {
      id: "road-minor-case",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 13,
      filter: ["in", "class", "minor", "service"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#e8e2da",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          0.8,
          14,
          1.4,
          15,
          2.8,
          16,
          4.4,
          18,
          10,
        ],
      },
    },
    {
      id: "road-minor-fill",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 13,
      filter: ["in", "class", "minor", "service"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#ffffff",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          0.2,
          14,
          0.8,
          15,
          1.7,
          16,
          3,
          18,
          7,
        ],
      },
    },
    {
      id: "road-path",
      type: "line",
      source: "carto",
      "source-layer": "transportation",
      minzoom: 15,
      filter: ["in", "class", "path", "track"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#d8d1c7",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          15,
          0.6,
          16,
          1,
          18,
          2.6,
        ],
        "line-dasharray": [2, 2],
      },
    },
    {
      id: "water-label-lake",
      type: "symbol",
      source: "carto",
      "source-layer": "water_name",
      minzoom: 13,
      filter: [
        "all",
        ["has", "name"],
        ["==", "class", "lake"],
      ],
      layout: {
        "text-field": "{name}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          10,
          17,
          13,
        ],
        "text-font": [
          "Montserrat Regular Italic",
          "Open Sans Italic",
          "Noto Sans Regular",
        ],
      },
      paint: {
        "text-color": "#7d95a0",
        "text-halo-color": "#f7f5f0",
        "text-halo-width": 1,
      },
    },
    {
      id: "place-village",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 10,
      maxzoom: 16,
      filter: ["==", "class", "village"],
      layout: {
        "text-field": "{name}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          10,
          10,
          14,
          13,
        ],
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
        ],
        "text-max-width": 10,
      },
      paint: {
        "text-color": "#657681",
        "text-halo-color": "#f7f5f0",
        "text-halo-width": 1,
      },
    },
    {
      id: "place-town",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 8,
      maxzoom: 15,
      filter: ["==", "class", "town"],
      layout: {
        "text-field": "{name}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          11,
          14,
          16,
        ],
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
        ],
        "text-max-width": 10,
      },
      paint: {
        "text-color": "#5d6d77",
        "text-halo-color": "#f7f5f0",
        "text-halo-width": 1,
      },
    },
    {
      id: "place-city",
      type: "symbol",
      source: "carto",
      "source-layer": "place",
      minzoom: 8,
      maxzoom: 16,
      filter: ["==", "class", "city"],
      layout: {
        "text-field": "{name}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          12,
          10,
          14,
          14,
          19,
        ],
        "text-font": [
          "Montserrat Medium",
          "Open Sans Bold",
          "Noto Sans Regular",
        ],
        "text-max-width": 10,
      },
      paint: {
        "text-color": "#55646e",
        "text-halo-color": "#f7f5f0",
        "text-halo-width": 1.2,
      },
    },
    {
      id: "road-label-major",
      type: "symbol",
      source: "carto",
      "source-layer": "transportation_name",
      minzoom: 13,
      filter: ["in", "class", "motorway", "trunk", "primary"],
      layout: {
        "symbol-placement": "line",
        "text-field": "{name}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          10,
          17,
          12,
        ],
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
        ],
        "symbol-spacing": 240,
      },
      paint: {
        "text-color": "#8d8984",
        "text-halo-color": "#fcfbf8",
        "text-halo-width": 1.2,
      },
    },
    {
      id: "road-label-secondary",
      type: "symbol",
      source: "carto",
      "source-layer": "transportation_name",
      minzoom: 15,
      filter: ["in", "class", "secondary", "tertiary"],
      layout: {
        "symbol-placement": "line",
        "text-field": "{name}",
        "text-size": [
          "interpolate",
          ["linear"],
          ["zoom"],
          15,
          9,
          17,
          11,
        ],
        "text-font": [
          "Montserrat Regular",
          "Open Sans Regular",
          "Noto Sans Regular",
        ],
        "symbol-spacing": 220,
      },
      paint: {
        "text-color": "#94908a",
        "text-halo-color": "#fcfbf8",
        "text-halo-width": 1,
      },
    },
  ],
});

export const DISCOVER_WEBVIEW_STYLE_JSON = JSON.stringify(
  DISCOVER_WEBVIEW_VECTOR_STYLE
);
